# Generated by Django 3.0.4 on 2020-05-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
