# Generated by Django 3.0.4 on 2020-05-09 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_auto_20200509_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rate',
        ),
    ]
