# Generated by Django 3.0.4 on 2020-05-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_remove_comment_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
