# Generated by Django 3.0.4 on 2020-05-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_auto_20200511_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
