# Generated by Django 3.0.4 on 2020-05-18 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_car_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.Category'),
        ),
    ]
