# Generated by Django 3.0.4 on 2020-05-25 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0019_auto_20200526_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='door',
        ),
        migrations.RemoveField(
            model_name='car',
            name='location',
        ),
        migrations.RemoveField(
            model_name='car',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='car',
            name='short_desc',
        ),
        migrations.RemoveField(
            model_name='car',
            name='vehicle_type',
        ),
    ]
