# Generated by Django 3.0.4 on 2020-06-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0020_auto_20200526_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('Benzin', 'Benzin'), ('LPG', 'LPG'), ('Dizel', 'Dizel'), ('Hybrid', 'Hybrid')], max_length=10),
        ),
    ]
