# Generated by Django 3.0.4 on 2020-06-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0021_auto_20200601_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='gear',
            field=models.CharField(choices=[('Manuel', 'Manuel'), ('Otomatik', 'Otomatik'), ('Yarı Otomatik', 'Yarı Otomatik')], max_length=15),
        ),
    ]
