# Generated by Django 3.0.4 on 2020-06-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0022_auto_20200601_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='situation',
            field=models.CharField(choices=[('Cabrio', 'Cabrio'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Sedan', 'Sedan')], max_length=10),
        ),
    ]
